server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:gateway-keystore.p12
    key-store-password: gateway@123
    key-store-type: PKCS12
    key-alias: gateway
spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: https://localhost:8081
          predicates:
            - Path=/patient/**
        - id: appointment-service
          uri: https://localhost:8082
          predicates:
            - Path=/appointment/**
    vault:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:9000
